---
# tasks file for ruby (Ubuntu specific)

- name: Install Ruby build dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items: ruby_build_dependencies
  tags: ruby

- name: Clone rbenv
  git: >
    repo=https://github.com/sstephenson/rbenv.git
    dest=/usr/local/rbenv
  tags: ruby

- name: Clone ruby-build plugin
  git: >
    repo=https://github.com/sstephenson/ruby-build.git
    dest=/usr/local/rbenv/plugins/ruby-build
  tags: ruby

- name: Create rbenv profile
  template: >
    src=rbenv.sh.j2
    dest=/etc/profile.d/rbenv.sh
    owner=root
    group=root
    mode=0644
  tags: ruby

- name: Create rbenv shims directory
  file: >
    path=/usr/local/rbenv/shims
    owner=root
    group=root
    mode=0755
    state=directory
  tags: ruby

- name: Create rbenv versions directory
  file: >
    path=/usr/local/rbenv/versions
    owner=root
    group=root
    mode=0755
    state=directory
  tags: ruby

- name: Install Ruby
  shell: rbenv install {{ ruby_version }}
  environment:
    PATH: /usr/local/rbenv/bin:{{ ansible_env.PATH }}
    RBENV_ROOT: /usr/local/rbenv
  args:
    creates: /usr/local/rbenv/versions/{{ ruby_version }}
  tags: ruby

- name: Get current global Ruby
  shell: rbenv global
  environment:
    PATH: /usr/local/rbenv/bin:{{ ansible_env.PATH }}
    RBENV_ROOT: /usr/local/rbenv
  register: global_ruby
  changed_when: false
  tags: ruby

- name: Configure global Ruby
  shell: rbenv global {{ ruby_version }}
  environment:
    PATH: /usr/local/rbenv/bin:{{ ansible_env.PATH }}
    RBENV_ROOT: /usr/local/rbenv
  changed_when: global_ruby.stdout != "{{ ruby_version }}"
  tags: ruby
